#!/usr/bin/python

import os, sys, sysconfig

ENTRY = 'cwordg.py'

path = os.path.join(sysconfig.get_paths()['purelib'], 'pycross', ENTRY)

if not os.path.isfile(path):
    path = os.path.join(os.path.abspath(os.path.dirname(__file__)), ENTRY)
    
if os.path.isfile(path):
    os.system(f'python "{path}"')
else:
    print(f'File "{path}" is inaccessible!', file=sys.stderr)
    sys.exit(1)